use_frameworks!

platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'DYCircleImage_Example' do
  pod 'DYCircleImage', :path => '../'

  target 'DYCircleImage_Tests' do
    inherit! :search_paths

    
  end
end
